spring:
  application:
    name: shellspell
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shellspell}
    username: ${SPRING_DATASOURCE_USERNAME:shellspell}
    password: ${SPRING_DATASOURCE_PASSWORD:shellspell}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 35
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

app:
  jwt:
    secret: ${JWT_SECRET:9a2f98287813b5d2b77a063b4f62557e1c8d7698547432f416e88514930d6bf4} # Hex 256-bit key for HMAC-SHA256
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

