apiVersion: v1
kind: Service
metadata:
  name: shellspell-frontend
  namespace: shellspell
  labels:
    app.kubernetes.io/name: shellspell-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: shellspell
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: shellspell-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
