apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shellspell
  namespace: shellspell
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cluster-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - shellspell.ygg.dedyn.io
      secretName: shellspell-tls
  rules:
    - host: shellspell.ygg.dedyn.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
